export const API_ENDPOINTS = {
  AUTH: "/auth",
  LOGIN: "/auth/login",
  LOGOUT: "/auth/logout",
  REGISTER: "/auth/register",
  ME: "/auth/me",
  PROFILE: "/auth/profile",
  CART: "/cart",
  CART_ITEMS: (productVariantId: number) => `/cart/items/${productVariantId}`,
  CHECKOUT: "/checkout",
  REFRESH_TOKEN: "/auth/refresh-token",
  ORDER: "/orders",
  ORDERCART: "/orders/cart",
  ORDERBUYNOW: "/orders/buynow",
  USERADDRESS: "/addresses",
  PAYMENT_ORDERCODE: (orderCode: string) => `/payment/${orderCode}`,
} as const;
