export const RAW_DATA = [
  {
    id: "SN-2026-001",
    name: "Điều hòa Daikin Inverter 1.5 HP",
    room: "101",
    status: "Ổn định",
    category: "Điện lạnh",
  },
  {
    id: "SN-2026-002",
    name: "Máy giặt LG TurboWash 10kg",
    room: "102",
    status: "Bảo trì",
    category: "Gia dụng",
  },
  {
    id: "SN-2026-003",
    name: "Tủ lạnh Samsung Bespoke",
    room: "101",
    status: "Ổn định",
    category: "Điện lạnh",
  },
  {
    id: "SN-2026-004",
    name: "Bếp từ Bosch Series 6",
    room: "201",
    status: "Lỗi kỹ thuật",
    category: "Gia dụng",
  },
  {
    id: "SN-2026-005",
    name: "Điều hòa Panasonic Nanoe-G",
    room: "202",
    status: "Ổn định",
    category: "Điện lạnh",
  },
  {
    id: "SN-2026-006",
    name: "Lò vi sóng Sharp 25L",
    room: "103",
    status: "Ổn định",
    category: "Gia dụng",
  },
  {
    id: "SN-2026-007",
    name: "Tivi Sony 4K 55 inch",
    room: "301",
    status: "Bảo trì",
    category: "Điện tử",
  },
  {
    id: "SN-2026-008",
    name: "Máy hút mùi Malloca",
    room: "201",
    status: "Ổn định",
    category: "Gia dụng",
  },
  {
    id: "SN-2026-009",
    name: "Bình nóng lạnh Ariston",
    room: "102",
    status: "Ổn định",
    category: "Điện nước",
  },
  {
    id: "SN-2026-010",
    name: "Điều hòa Daikin Inverter 1.0 HP",
    room: "401",
    status: "Lỗi kỹ thuật",
    category: "Điện lạnh",
  },
  {
    id: "SN-2026-011",
    name: "Máy lọc nước Kangaroo",
    room: "103",
    status: "Ổn định",
    category: "Điện nước",
  },
  {
    id: "SN-2026-012",
    name: "Quạt trần Panasonic 5 cánh",
    room: "302",
    status: "Ổn định",
    category: "Gia dụng",
  },
  {
    id: "SN-2026-013",
    name: "Khóa cửa thông minh Kaadas",
    room: "P.VIP",
    status: "Ổn định",
    category: "An ninh",
  },
  {
    id: "SN-2026-014",
    name: "Máy sấy quần áo Electrolux",
    room: "Laundry",
    status: "Bảo trì",
    category: "Gia dụng",
  },
  {
    id: "SN-2026-015",
    name: "Router Wifi Asus ROG",
    room: "Hành lang",
    status: "Ổn định",
    category: "Viễn thông",
  },
  {
    id: "SN-2026-016",
    name: "Camera Hikvision 4MP",
    room: "Bãi xe",
    status: "Lỗi kỹ thuật",
    category: "An ninh",
  },
  {
    id: "SN-2026-017",
    name: "Đèn chùm pha lê Italy",
    room: "Sảnh",
    status: "Ổn định",
    category: "Nội thất",
  },
  {
    id: "SN-2026-018",
    name: "Máy pha cà phê Delonghi",
    room: "P.Chung",
    status: "Ổn định",
    category: "Gia dụng",
  },
  {
    id: "SN-2026-019",
    name: "Máy chiếu Epson EB-X06",
    room: "P.Họp",
    status: "Bảo trì",
    category: "Điện tử",
  },
  {
    id: "SN-2026-020",
    name: "Tủ rượu vang Kadeka",
    room: "P.VIP",
    status: "Ổn định",
    category: "Gia dụng",
  },
];
