export const TENANTS = [
  {
    id: "TEN-1024",
    name: "Nguyễn Văn Anh",
    email: "anhnv@gmail.com",
    phone: "0987 654 321",
    room: "101",
    joinDate: "15 Jan, 2026",
    status: "active",
    avatar: "https://github.com/shadcn.png",
    identityVerified: true,
    contractEnd: "15 Jan, 2027",
    hasVehicle: "yes",
  },
  {
    id: "TEN-1025",
    name: "Trần Thị Bảo",
    email: "baott@yahoo.com",
    phone: "0912 333 444",
    room: "102",
    joinDate: "10 Feb, 2026",
    status: "expiring",
    avatar: "",
    identityVerified: false,
    contractEnd: "10 May, 2026",
    hasVehicle: "yes",
  },
  {
    id: "TEN-0982",
    name: "Lê Minh Công",
    email: "congl@outlook.com",
    phone: "0345 111 222",
    room: "201",
    joinDate: "01 Dec, 2025",
    status: "inactive",
    avatar: "",
    identityVerified: true,
    contractEnd: "01 Dec, 2026",
    hasVehicle: "no",
  },
  {
    id: "TEN-1026",
    name: "Phạm Minh Tuấn",
    email: "tuanpm@gmail.com",
    phone: "0945 888 999",
    room: "103",
    joinDate: "01 Mar, 2026",
    status: "active",
    avatar: "",
    identityVerified: true,
    contractEnd: "01 Mar, 2027",
    hasVehicle: "yes",
  },
  {
    id: "TEN-1027",
    name: "Hoàng Thu Thảo",
    email: "thaoth@hotmail.com",
    phone: "0967 111 222",
    room: "204",
    joinDate: "05 May, 2026",
    status: "active",
    avatar: "",
    identityVerified: false,
    contractEnd: "05 Nov, 2026",
    hasVehicle: "yes",
  },
  {
    id: "TEN-1028",
    name: "Vũ Hải Đăng",
    email: "dangvh@gmail.com",
    phone: "0915 222 333",
    room: "401",
    joinDate: "20 Jan, 2026",
    status: "expiring",
    avatar: "",
    identityVerified: true,
    contractEnd: "20 Jun, 2026",
    hasVehicle: "no",
  },
  {
    id: "TEN-0975",
    name: "Đặng Thị Mai",
    email: "maidt@gmail.com",
    phone: "0388 444 555",
    room: "104",
    joinDate: "15 Apr, 2025",
    status: "inactive",
    avatar: "",
    identityVerified: true,
    contractEnd: "15 Apr, 2026",
    hasVehicle: "no",
  },
  {
    id: "TEN-1029",
    name: "Bùi Quang Huy",
    email: "huybq@yahoo.com",
    phone: "0972 666 777",
    room: "302",
    joinDate: "01 Apr, 2026",
    status: "active",
    avatar: "",
    identityVerified: false,
    contractEnd: "01 Apr, 2027",
    hasVehicle: "yes",
  },
  {
    id: "TEN-1030",
    name: "Ngô Quốc Bảo",
    email: "baonq@outlook.com",
    phone: "0934 555 666",
    room: "202",
    joinDate: "10 Feb, 2026",
    status: "active",
    avatar: "",
    identityVerified: true,
    contractEnd: "10 Feb, 2027",
    hasVehicle: "yes",
  },
  {
    id: "TEN-1031",
    name: "Đỗ Thùy Linh",
    email: "linhdt@gmail.com",
    phone: "0981 222 444",
    room: "405",
    joinDate: "15 May, 2026",
    status: "active",
    avatar: "",
    identityVerified: true,
    contractEnd: "15 May, 2027",
    hasVehicle: "no",
  },
  // --- Dữ liệu mặc định sẽ tràn sang trang số 2 ---
  {
    id: "TEN-1032",
    name: "Lý Hoàng Nam",
    email: "namlh@gmail.com",
    phone: "0904 777 888",
    room: "301",
    joinDate: "15 Mar, 2026",
    status: "expiring",
    avatar: "",
    identityVerified: false,
    contractEnd: "15 Jun, 2026",
    hasVehicle: "yes",
  },
  {
    id: "TEN-1033",
    name: "Trịnh Công Sơn",
    email: "sontc@gmail.com",
    phone: "0919 333 111",
    room: "102",
    joinDate: "10 May, 2026",
    status: "active",
    avatar: "",
    identityVerified: true,
    contractEnd: "10 May, 2027",
    hasVehicle: "yes",
  },
  {
    id: "TEN-1034",
    name: "Phan Thanh Bình",
    email: "binhpt@gmail.com",
    phone: "0982 555 444",
    room: "304",
    joinDate: "01 Jan, 2026",
    status: "active",
    avatar: "",
    identityVerified: true,
    contractEnd: "01 Jan, 2027",
    hasVehicle: "no",
  },
  {
    id: "TEN-1035",
    name: "Vũ Phương Thảo",
    email: "thaovp@yahoo.com",
    phone: "0963 999 888",
    room: "402",
    joinDate: "12 Feb, 2026",
    status: "expiring",
    avatar: "",
    identityVerified: false,
    contractEnd: "12 Jun, 2026",
    hasVehicle: "yes",
  },
  {
    id: "TEN-0960",
    name: "Nguyễn Minh Triết",
    email: "trietnm@outlook.com",
    phone: "0352 777 111",
    room: "305",
    joinDate: "10 Oct, 2025",
    status: "inactive",
    avatar: "",
    identityVerified: true,
    contractEnd: "10 Apr, 2026",
    hasVehicle: "no",
  },
];
